const categoriesData = [
  { id: 1, name: "Handyman Services", icon: "🔧" },
  { id: 2, name: "Plumbing", icon: "🚿" },
  { id: 3, name: "Electrical Work", icon: "⚡" },
  { id: 4, name: "Painting", icon: "🎨" },
  { id: 5, name: "Furniture Assembly", icon: "🪑" },
  { id: 6, name: "Gardening", icon: "🌱" },
  { id: 7, name: "House Cleaning", icon: "🧹" },
  { id: 8, name: "Office Cleaning", icon: "🏢" },
  { id: 9, name: "End-of-Lease Cleaning", icon: "🏠" },
  { id: 10, name: "Help with Moving House", icon: "📦" },
  { id: 11, name: "Relocating Furniture", icon: "🪑" },
  { id: 12, name: "Disposing Unwanted Items", icon: "🗑️" },
  { id: 13, name: "Delivery and Courier Services", icon: "🚚" },
  { id: 14, name: "Delivering Package", icon: "📦" },
  { id: 15, name: "Groceries or Other Items", icon: "🛒" },
  { id: 16, name: "Event Planning", icon: "🎉" },
  { id: 17, name: "Catering", icon: "🍽️" },
  { id: 18, name: "Photography", icon: "📷" },
  { id: 19, name: "Party Assistance", icon: "🎈" },
  { id: 20, name: "Personal Training", icon: "💪" },
  { id: 21, name: "Beauty and Grooming", icon: "💇" },
  { id: 22, name: "Pet Care", icon: "🐾" },
  { id: 23, name: "Tech Support", icon: "💻" },
  { id: 24, name: "Software Installation", icon: "💿" },
  { id: 25, name: "Computer Repair", icon: "🔧" },
  { id: 26, name: "Assistance with Shopping", icon: "🛍️" },
  { id: 27, name: "Walking in Garden", icon: "🌿" },
  { id: 28, name: "Copywriting", icon: "📝" },
  { id: 29, name: "Proofreading", icon: "✒️" },
  { id: 30, name: "Graphic Design", icon: "🎨" },
  { id: 31, name: "Content Creation", icon: "📄" },
  { id: 32, name: "Virtual Assistance", icon: "💼" },
  { id: 33, name: "Social Media Management", icon: "📱" },
  { id: 34, name: "Website Development", icon: "🌐" },
  { id: 35, name: "Translation Services", icon: "🌍" },
  { id: 36, name: "Marketing Tasks", icon: "📈" },
  { id: 37, name: "Organize, Pack, and Unpack", icon: "📦" },
  { id: 38, name: "Tutoring & Training", icon: "🎓" },
  { id: 39, name: "Hair & Beauty", icon: "💇" },
  { id: 40, name: "Fitness Trainer (Yoga)", icon: "🧘" },
  { id: 41, name: "Floor Tiling", icon: "🪟" },
  { id: 42, name: "Fencing", icon: "🪚" },
  { id: 43, name: "Household Installs & Repairs", icon: "🔩" },
  { id: 44, name: "Clothing Alteration & Repairs", icon: "👗" },
  { id: 45, name: "Nanny & Babysitting", icon: "👶" },
  { id: 46, name: "Lifestyle", icon: "🌟" },
  { id: 47, name: "Fun & Quirky", icon: "🎉" },
  { id: 48, name: "Sewing and Alterations", icon: "🧵" },
  { id: 49, name: "Pest Control Services", icon: "🐜" },
  { id: 50, name: "3D Printing Services", icon: "🖨️" },
  { id: 51, name: "Resume & Cover Letter Writing", icon: "📃" },
  { id: 52, name: "Housekeeping", icon: "🏡" },
  { id: 53, name: "Financial Consultant", icon: "💼" },
  { id: 54, name: "Safety", icon: "🚧" },
  { id: 55, name: "Mental and Emotional Support", icon: "❤️" },
  { id: 56, name: "Medical Care", icon: "⚕️" },
  { id: 57, name: "Listener", icon: "👂" },
  { id: 58, name: "Physiotherapy", icon: "🏥" },
  { id: 59, name: "Dance Teacher", icon: "💃" },
  { id: 60, name: "Society Manager", icon: "🏢" },
  { id: 61, name: "Writer for Exam", icon: "📝" },
  { id: 62, name: "Mobile Repairing", icon: "📱" },
  { id: 63, name: "Cooking", icon: "🍳" },
  // ...other categories
];

export default categoriesData;
